Student.WebUI/Controllers/ExamController.cs
using Microsoft.AspNet.Identity.Owin;
using Student.BLL.DTO;
using Student.BLL.Interfaces;
using Student.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Student.WebUI.Controllers
{
    public class ExamController : Controller
    {
        private IExamService ExamService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IExamService>();
            }
        }
        private IStudentGroupService StudentGroupService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IStudentGroupService>();
            }
        }

        private ILessonService LessonService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ILessonService>();
            }
        }
        private IQuestionService QuestionService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IQuestionService>();
            }
        }
        private IOptionsService OptionsService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IOptionsService>();
            }
        }
        private IStudentService StudentService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IStudentService>();
            }
        }

        public ViewResult Index()
        {
            return View(ExamService.GetAll());
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ViewResult addExam()
        {
            ViewBag.Groups = StudentGroupService.GetAll();
            ViewBag.Lessons = LessonService.GetAll();
            return View(new ExamViewModel());
        }
        [HttpPost]
        public ActionResult addExam(ExamViewModel model)
        {
            if (ModelState.IsValid)
            {
                var op = ExamService.Create(new BLL.DTO.ExamDTO() { Id = model.Id, /*Created = DateTime.Now,*/ Duration = model.Duration, ExamDate = model.ExamDate, FullMark= model.FullMark, GroupId = model.GroupId, LessonId = model.LessonId});
                TempData["message"] = string.Format("{0} has been saved", op.Message);
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                // there is something wrong with the data values
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult ExamGroup(int id)
        {
            var deletedGroup = ExamService.Delete(id);
            if (deletedGroup != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedGroup.Id);
            }
            return RedirectToAction("Index", "Admin");
        }

        public ViewResult EditExam(int id)
        {
            var exam = ExamService.GetById(id);
            var model = new ExamViewModel() { Id = exam.Id, Created = DateTime.Now, Duration = exam.Duration, ExamDate = exam.ExamDate, FullMark = exam.FullMark, GroupId = exam.GroupId, LessonId = exam.LessonId };
            return View(model);
        }

        [HttpPost]
        public ActionResult EditExam(ExamViewModel model)
        {
            if (ModelState.IsValid)
            {
                ExamService.Create(new BLL.DTO.ExamDTO() { Id = model.Id, /*Created = DateTime.Now,*/ Duration = model.Duration, ExamDate = model.ExamDate, FullMark = model.FullMark, GroupId = model.GroupId, LessonId = model.LessonId });
                TempData["message"] = string.Format("{0} has been saved", model.Id);
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                // there is something wrong with the data values
                return View(model);
            }
        }


        [Authorize(Roles = "admin")]
        [HttpGet]
        public ViewResult AddQuestion()
        {
            ViewBag.Groups = StudentGroupService.GetAll();
            ViewBag.Lessons = LessonService.GetAll();
            return View(new ExamViewModel());
        }
        [HttpPost]
        public ActionResult AddQuestion(ExamViewModel model)
        {
            if (ModelState.IsValid)
            {
                var op = ExamService.Create(new BLL.DTO.ExamDTO() { Id = model.Id, /*Created = DateTime.Now,*/ Duration = model.Duration, ExamDate = model.ExamDate, FullMark = model.FullMark, GroupId = model.GroupId, LessonId = model.LessonId });
                TempData["message"] = string.Format("{0} has been saved", op.Message);
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                // there is something wrong with the data values
                return View(model);
            }
        }
        [Authorize(Roles = "admin, user")]
        [HttpGet]
        public ViewResult TakeExam(int examid)
        {
            var QuestionAnswer= new List<QuestionAnswerViewModel>();
            var questions = QuestionService.GetByExamId(examid);
            foreach(var item in questions)
            {
                QuestionAnswer.Add(new QuestionAnswerViewModel { question = item, options = OptionsService.GetbyQuestionid(item.Id)});
            }
            ViewBag.QnAns = QuestionAnswer;
            return View(new ExamResultDTO());
        }
        [HttpPost]
        public ActionResult TakeExam(ExamResultDTO model)
        {
            
            if (ModelState.IsValid)
            {
                //var op = ExamService.Create(new BLL.DTO.ExamDTO() { Id = model.Id, /*Created = DateTime.Now,*/ Duration = model.Duration, ExamDate = model.ExamDate, FullMark = model.FullMark, GroupId = model.GroupId, LessonId = model.LessonId });
                //TempData["message"] = string.Format("{0} has been saved", op.Message);
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                // there is something wrong with the data values
                return View(model);
            }
        }
    }
}

Student.WebUI/Controllers/HomeController.cs
using Microsoft.AspNet.Identity.Owin;
using Student.BLL.Interfaces;
using Student.DAL.EF;
using Student.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Student.WebUI.Controllers
{
    public class HomeController : Controller
    {
        EFDbContext LessonContext;
        private IExamService ExamService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IExamService>();
            }
        }
        private IStudentService StudentService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IStudentService>();
            }
        }
        public HomeController()
        {
            LessonContext = new EFDbContext("DefaultConnection1");
        }
        public ActionResult Index(string UserId)
        { 
            var q = ExamService.GetbyGroupId(StudentService.GetById(UserId).Groupid);

            var evals = from u in LessonContext.Evaluations.Where(p => p.UserId == UserId)
                        join c in LessonContext.Exams on u.ExamId equals c.Id
                        join l in LessonContext.Lessons on c.LessonId equals l.LessonId
                        select new StudentViewModel { Date = c.ExamDate, Lesson = l.Name, Value = u.Value };

            ViewBag.Exams = q; 
            //IQueryable<Guid> ExamIds = Enumerable.Empty<Guid>().AsQueryable();
            //var evals = from u in ClientContext.ClientProfiles.Where(p => p.Id == UserId)
            //            join sg in LessonContext.GroupLessons on u.StudentGroupId equals sg.GroupId
            //            join e in LessonContext.Exams on sg.LessonId equals e.LessonId
            //            join l in LessonContext.Lessons on e.LessonId equals l.LessonId
            //            select new StudentViewModel { Date = e.ExamDate, Lesson = l.Name, Value = new double() };

            return View(evals.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Student.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Student.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
@if (User.IsInRole("admin"))
{
    <h2>admin!</h2>
}
<address>

    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Student.WebUI/Views/Home/Index.cshtml
@model List<Student.WebUI.Models.StudentViewModel>
@{
    ViewBag.Title = "Home Page";
    var Exams = (List<Student.BLL.DTO.ExamDTO>)ViewBag.Exams;
}

<h2>@User.Identity.Name</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <div>All Exams</div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ExamId</th>
                <th>Group</th>
                <th>Lesson</th>
                <th>Date</th>
                <th>Duration</th>
                <th>Full Mark</th>
            </tr>
            @foreach (var item in Exams)
            {
        <tr>
            <td class="text-right">@item.Id</td>
            <td>@item.GroupId</td>
            <td>@item.LessonId</td>
            <td>@item.ExamDate.ToString("dd/MM/yyyy hh:mm")</td>
            <td>@item.Duration</td>
            <td>@item.FullMark</td>
            <td>
                @Html.ActionLink("Take Exam", "TakeExam", "Exam", new { examid = item.Id }, new { @class = "btn btn-default  btn-xs" })
            </td>
            @*<td class="text-right">@item.LessonId</td>
        <td class="text-right">@item.Name</td>*@
        </tr>
            }
        </table>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <div>All Evaluetions</div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">Date</th>
                <th>Lesson</th>
                <th>Value</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.Date.ToString("dd/MM/yyyy")</td>
                    <td>@item.Lesson</td>
                    <td>@item.Value</td>
                </tr>
            }
        </table>
    </div>
</div>